repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.5
  hooks:
    # Run the linter
    - id: ruff
      args: [ --fix, --no-cache ]
    # Run the formatter
    - id: ruff-format
      args: [ --no-cache, --respect-gitignore ]